# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LensDataEditor', '0002_auto_20160424_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='surface',
            name='surfaceIndex',
            field=models.IntegerField(default=0),
        ),
    ]
