# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LensDataEditor', '0003_surface_surfaceindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='surface',
            name='surfaceMaterial',
            field=models.CharField(default='Air', max_length=20),
        ),
        migrations.AlterField(
            model_name='surface',
            name='surfaceType',
            field=models.CharField(max_length=10),
        ),
    ]
