# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LensDataEditor', '0004_auto_20160427_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raySetIndex', models.IntegerField()),
                ('raySetGridType', models.CharField(max_length=20)),
                ('raySetGridDensity', models.IntegerField(default=4)),
                ('raySetAngleX', models.FloatField(default=0.0)),
                ('raySetAngleY', models.FloatField(default=0.0)),
                ('raySetWavelength', models.FloatField(default=0.55)),
            ],
        ),
    ]
