# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LensDataEditor', '0005_rayset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rayset',
            old_name='raySetAngleX',
            new_name='raysetAngleX',
        ),
        migrations.RenameField(
            model_name='rayset',
            old_name='raySetAngleY',
            new_name='raysetAngleY',
        ),
        migrations.RenameField(
            model_name='rayset',
            old_name='raySetGridDensity',
            new_name='raysetGridDensity',
        ),
        migrations.RenameField(
            model_name='rayset',
            old_name='raySetGridType',
            new_name='raysetGridType',
        ),
        migrations.RenameField(
            model_name='rayset',
            old_name='raySetIndex',
            new_name='raysetIndex',
        ),
        migrations.RenameField(
            model_name='rayset',
            old_name='raySetWavelength',
            new_name='raysetWavelength',
        ),
    ]
