# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LensDataEditor', '0006_auto_20160511_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rayset',
            old_name='raysetAngleX',
            new_name='raySetAngleX',
        ),
        migrations.RenameField(
            model_name='rayset',
            old_name='raysetAngleY',
            new_name='raySetAngleY',
        ),
        migrations.RenameField(
            model_name='rayset',
            old_name='raysetGridDensity',
            new_name='raySetGridDensity',
        ),
        migrations.RenameField(
            model_name='rayset',
            old_name='raysetGridType',
            new_name='raySetGridType',
        ),
        migrations.RenameField(
            model_name='rayset',
            old_name='raysetIndex',
            new_name='raySetIndex',
        ),
        migrations.RenameField(
            model_name='rayset',
            old_name='raysetWavelength',
            new_name='raySetWavelength',
        ),
    ]
