# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LensDataEditor', '0007_auto_20160512_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='surface',
            name='surfaceConicConstantOptable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surface',
            name='surfaceDecenterXOptable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surface',
            name='surfaceDecenterYOptable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surface',
            name='surfaceMaterialOptable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surface',
            name='surfaceThicknessOptable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surface',
            name='surfaceVertexCurvatureOptable',
            field=models.BooleanField(default=False),
        ),
    ]
