# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LensDataEditor', '0008_auto_20160512_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='surface',
            name='surfaceRadiusOptable',
            field=models.BooleanField(default=False),
        ),
    ]
