# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LensDataEditor', '0009_surface_surfaceradiusoptable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Composition', models.CharField(max_length=100)),
                ('A1', models.FloatField(default=0.0)),
                ('B1', models.FloatField(default=0.0)),
                ('A2', models.FloatField(default=0.0)),
                ('B2', models.FloatField(default=0.0)),
                ('A3', models.FloatField(default=0.0)),
                ('B3', models.FloatField(default=0.0)),
            ],
        ),
    ]
